services:
  database:
    image: postgres:alpine3.19
    container_name: database.imptel
    restart: always
    ports:
      - 7001:5432
    networks:
      - inner-link
    environment:
      POSTGRES_USER: database.imptel
      POSTGRES_PASSWORD: Imp7e1_db
      POSTGRES_DATABASE: database.imptel
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  
  session:
    image: redis:alpine3.19
    container_name: database.imptel.session
    restart: always
    ports:
      - 7002:6379
    networks:
      - inner-link
    command: ["sh", "-c", "redis-server /etc/redis/redis.conf --save 20 1 --loglevel warning --daemonize yes && /docker-entrypoint-initdb.d/10-initial.sh && tail -f /dev/null"]
    volumes:
      - session-data:/data
      - ./redis:/docker-entrypoint-initdb.d
      - ./redis/redis.conf:/etc/redis/redis.conf


  account-service:
    image: account-service:1.0
    restart: always
    networks:
      - inner-link
    environment:
      DB_USER: database.imptel
      DB_PASSWORD: Imp7e1_db
      DB_HOST: database.imptel
      DB_PORT: 5432
      DB_NAME: database.imptel
      REDIS_HOST: database.imptel.session
      REDIS_PORT: 6379
      REDIS_PASSWORD: Imp7e1_db_session
    deploy:
      replicas: 2
    
    

volumes:
  database-data:
    name: database-data
  session-data:
    name: session-data


networks:
  inner-link:
    name: inner-link